### ISSUE TITLE
Support the full extent of the encryption module configurability

### ISSUE THREAD

**Issue by robobario** [kroxylicious/topic-encryption#3]
Currently we use a hardcoded test-kms only, that offers up a hardcoded key. Lets support some real KMS implementations :grin: 

The encryption module is configured by two configuration files loaded with Jackson. We could embed these configuration classes directly into our YAML configuration, or instead reference the two files from the kroxy configuration YAML, loading them exactly as the encmod would. Or support both styles.

For vault integration it would be cool to integration test it with a [vault testcontainer](https://java.testcontainers.org/modules/vault). Maybe there's something out there for key-protect testing too.

We currently only support the test-kms, to build the others into a fat jar will require combining their META-INF. Or we could remove the KMS implementations from the fat jar and install them separately into the Kroxylicious classpath.

Here's an example of the[ JSON configuration](https://github.com/kroxylicious/topic-encryption/tree/main/encmod/src/test/resources)

### embedded YAML style

`kroxylicious-config.yaml`
``` yaml
filters:
  type: TopicEncryption::DecryptFetch
  config:
    kmsDefs:
      - name: cloud
        type: key-protect
        uri: http://sfsffs.ibm.com/abc
        instanceId: shdjkjahkjahd
        credential: <apikey>
    topicPolicies:
      - name: topicA
        kmsName: cloud
        keyReference: topicAKey
```

### separate configuration with references

`kroxylicious-config.yaml`
``` yaml
filters:
  type: TopicEncryption::DecryptFetch
  config:
    kmsDefsFile: "/path/to/kmsdefs.json"
    topicPoliciesFile: "/path/to/topicPolicies.json"
```
